name: Build and Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Docker Build and Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t andreeaene/hopeshare-backend:${{ github.sha }} .
          docker tag andreeaene/hopeshare-backend:${{ github.sha }} andreeaene/hopeshare-backend:latest
          docker push andreeaene/hopeshare-backend:${{ github.sha }}
          docker push andreeaene/hopeshare-backend:latest

      - name: Deploy to Self-Hosted Server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/hopeshar
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            echo "REST_API_BE=${{ secrets.REST_API_BE }}" >> .env
            echo "REST_API_FE=${{ secrets.REST_API_FE }}" >> .env
            echo "REST_API_GOOGLE_CLIENT_ID=${{ secrets.REST_API_GOOGLE_CLIENT_ID }}" >> .env
            echo "REST_API_GOOGLE_CLIENT_SECRET=${{ secrets.REST_API_GOOGLE_CLIENT_SECRET }}" >> .env
            echo "REST_API_GOOGLE_REDIRECT_URI=${{ secrets.REST_API_GOOGLE_REDIRECT_URI }}" >> .env
            echo "REST_API_USER_EMAIL=${{ secrets.REST_API_USER_EMAIL }}" >> .env
            echo "REST_API_USER_PASSWORD=${{ secrets.REST_API_USER_PASSWORD }}" >> .env
            echo "REST_API_UVTSIGN_TOKEN=${{ secrets.REST_API_UVTSIGN_TOKEN }}" >> .env
            echo "REST_API_PRIVATE_KEY=${{ secrets.REST_API_PRIVATE_KEY }}" >> .env
            echo "REST_API_PUBLIC_KEY=${{ secrets.REST_API_PUBLIC_KEY }}" >> .env
            docker-compose pull
            docker-compose up -d
